CREATE TABLE cliente(
id BIGINT NOT NULL AUTO_INCREMENT,
nome VARCHAR(60) NOT NULL,
email VARCHAR(250) UNIQUE NOT NULL,
telefone VARCHAR(20) NOT NULL,

PRIMARY KEY(id)
);
/*ENGINE=INNODB DEFAULT CHARSET=UTF8;*/
/* ALTER TABLE cliente RENAME COLUMN telefone TO fone*/
